graph TB
    subgraph Node
        direction TB
        subgraph P1 [Pod]
            direction LR
            C1["Container"]
            C2["Container"]
        end

        subgraph P2 [Pod]
            C3["Container"]
        end
    end