pie title 项目取消/失败原因
    "需求不完整" : 13.1
    "缺乏用户参与" : 12.4
    "资源不足" : 10.6
    "期望不现实" : 9.9
    "缺乏高层支持" : 9.3
    "需求与规格频繁变更" : 8.7
    "缺乏规划" : 8.1
    "不再需要该项目" : 7.5
    "缺乏IT管理" : 6.2
    "技术文盲" : 4.3